server:
  port: 2023
spring:
  application:
    name: gbha-libro-service

  datasource:
    url: CONFIGURACION NEON
    username: neondb_owner (USUARIO)
    password: CONTRASEÑA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2020/eureka
  instance:
    hostname: localhost
