server:
  port: 2999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2020/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: gbha-libro-service
          uri: lb://gbha-libro-service
          predicates:
            - Path=/libro/**, /profession/**

        - id: gbha-usuario-service
          uri: lb://gbha-usuario-service
          predicates:
            - Path=/usuario/**

        - id: gbha-prestamo-service
          uri: lb://gbha-prestamo-service
          predicates:
            - Path=/prestamos/**
