server:
  port: 2024
spring:
  application:
    name: gbha-usuario-service
  datasource:
    url: jdbc:postgresql://ep-young-brook-a4jkg7zu-pooler.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_IT01BDrCNatA&sslmode=require
    username: neondb_owner
    password: npg_IT01BDrCNatA
    driver-class-name: org.postgresql.Driver
        
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2020/eureka
  instance:
    hostname: localhost
